name: 🌲 Redwood build, lint, diagnostics, and tests
description: Run CI on a Redwood Project

inputs:
  node-version:
    description: The Node Version
    default: 18
  project-directory:
    description: Path to project directory
    required: true
  yarn3-cache:
    description: Enable Yarn 3 caching ('yes' or 'no' as string) 
    default: 'yes'    
  run-lint:
    description: Run project lint ('yes' or 'no' as string)
    default: 'yes'

defaults:
  run:
    shell: bash
    working-directory: ${{ inputs.project-directory }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: ⬢ Enable Corepack
      run: corepack enable

    - name: ⬢ Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: 🐘 Set up Postgres
      uses: CasperWA/postgresql-action@v1
      with:
        postgresql version: 14
        postgresql db: test
        postgresql user: test
        postgresql password: password

    - name: 📁 Get yarn cache directory path
      if: ${{ inputs.yarn3-cache == 'yes' }}
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: 📁 Cache yarn
      if: ${{ inputs.yarn3-cache == 'yes' }}
      uses: actions/cache@v3    
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: 🐈 Yarn install
      run: yarn install --inline-builds

    - name: ◭ Run migrate
      run: yarn rw prisma migrate dev
      env:
        DATABASE_URL: postgresql://test:password@localhost:5432/test
      
    - name: 🏗️ Run build
      run: yarn rw build
      env:
        DATABASE_URL: postgresql://test:password@localhost:5432/test

    - name: 🔎 Run lint
      if: ${{ inputs.run-lint == 'yes' }}
      run: yarn rw lint

    - name: 🔬 Run diagnostics
      run: yarn rw check
      
    - name: 🧪 Run tests
      run: |
        yarn rw test api --no-watch
        yarn rw test web --no-watch
      env:
        TEST_DATABASE_URL: postgresql://test:password@localhost:5432/test
